spring.application.name=rag-ai

spring.ai.openai.api-key=${OPEN_AI_KEY}
spring.ai.openai.chat.model=gpt-4o

spring.ai.vectorstore.pgvector.initialize-schema=true

logging.level.org.springframework.boot.docker.compose=DEBUG
logging.level.com.zaxxer.hikari=DEBUG